language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install -e .
  - pip install pytest gevent mypy

script:
  - mypy outplan
  - pytest -vv -s tests/

deploy:
  provider: pypi
  user: xiachufang
  password:
    secure: Z5OGq5Ph0GCuS4XInGGBg8gxFm1phz3mQ5cIOpkK64S5BXadKXTl+qAWLlGUPGoVVsB462MSvinU8GUAoLfzSq/uXMWAkkBy3Wek4s45pjMVbGUe0ZDffUFS77q5Y7VN/3Jtst4HZC23MYSMYeWvs5XmqfM5jY/1kHB8x5wYCm4Rm9Hhp8nUsFZI0sGsFv4/zUydfh12l6vAKFL3k93qUSIFbGnAAVjrEcoAHFUXLMOTwOgvE8WaMwm/VK91JMW0YaD69fMukrfianplFBX4RY0ZPzScOxPZWw+Kc/7A2tmviPy1gybm7lMLpdctjdBpOKFr1rccJ58V7p52lropcRQeJjJfIjqFTegoeXm7paaDDIOi8Z8Rvfxt8F8ks3ipKXcxITjZR1uIvDSKsEHy4+XZrAgnLlwoAk+FT3zXQVuVteoVMEvDtb9kRHiuhG7BkzH89XNSKx2t94vmawyX0C026spGpLW8eQkjASXMP5agDh6r42g9t6NitOtcrGSRHqneTvreO0lVt5rPHL/QIa8AGn9qerZXJ3Wf5LBunRf8RJOtFNgMSRp9oxYzyUcWcUwIsjmw2FW4vBfjgSseUcc78XUqBnFKxJQAPE88zNMFGlSugJInjioJdqumIgLNt3TkdYqQJgWV6wYBIJ+WJQnR+AFVH42Wq9dtKXdeGr4=
  on:
    repo: xiachufang/outplan
    tags: true
